### ISSUE TITLE
Whats wrong

### ISSUE THREAD

**Issue by lenorio** [kefir500/apk-editor-studio#139] opened 2024-02-02 11:33 UTC
```
I: Using Apktool 2.9.1 on Kojima.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\lenorio\AppData\Local\apk-editor-studio\frameworks\1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying raw classes.dex file...
I: Copying raw classes10.dex file...
I: Copying raw classes11.dex file...
I: Copying raw classes12.dex file...
I: Copying raw classes13.dex file...
I: Copying raw classes14.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying raw classes5.dex file...
I: Copying raw classes6.dex file...
I: Copying raw classes7.dex file...
I: Copying raw classes8.dex file...
I: Copying raw classes9.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 148: C:\Users\lenorio\AppData\Local\Temp\apk-editor-studio\apk\{68a81aa2-af17-4c7d-b34a-83433afda6eb}\original\META-INF\thing\mcHeader_com.thing.smart.v8:j2v8_thingMC.meta
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230)
	at java.base/java.io.File.toPath(File.java:2353)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:97)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:72)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.ApkDecoder.copyOriginalFiles(ApkDecoder.java:304)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:166)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
```
How to solve it?

**Comment by kefir500** [comment] 2024-03-11 04:22
Looks like [this issue](https://github.com/iBotPeaches/Apktool/issues/1460) from the Apktool (the underlying utility) repo.
The issue is marked as a windows-related bug, and is still open, unfortunately.

**Comment by kefir500** [comment] 2024-05-27 12:08
Closing as related to a third-party tool.

**Closed by kefir500** 2024-05-27 12:08 UTC
Labels: Apktool
