### ISSUE TITLE
Warning about change of encoding or retain encoding

### ISSUE THREAD

**Issue by h-h-h-h** [kefir500/apk-editor-studio#17] opened 2020-02-25 14:40 UTC
I had a UTF-16-encoded XML file with [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) that started with:

```xml
<?xml version="1.0" encoding="utf-16"?>
```

After editing the file, the discrepancy between `encoding="utf-16"` and a UTF-8-encoded file broke the app. I didn't immediately realize that and had to do some digging and comparing. (When I did, I changed the text to `encoding="utf-8"`.)

So, a solution would be to do what the title says. If the second option has to wait, the first option may be a quick fix that should be prioritized (message should include a word on the above problem).

**Comment by kefir500** [comment] 2020-03-06 18:17
Seems that Qt can detect UTF encodings only when the BOM is present (see [`qtextcodec.cpp`](https://code.woboq.org/qt5/qtbase/src/corelib/codecs/qtextcodec.cpp.html#_ZN10QTextCodec15codecForUtfTextERK10QByteArrayPS_)).
I changed the internal open/save algorithm for the code editor in the following way:

#### Open:
- Qt tries to detect the file encoding.
- The fallback encoding is UTF-8.
- The encoding is stored in a variable so it can be retained later when saving.

#### Save:
- If the encoding is UTF-8, **no** BOM is written.
- If the encoding is some other Unicode encoding, then the BOM **is** written.
- Otherwise, no BOM is written.

Please, check out this developer build and let me know if the problem is fixed.
https://github.com/kefir500/apk-editor-studio/releases/tag/development

**Comment by h-h-h-h** [comment] 2020-03-30 06:53
Unfortunately, there are bad VirusTotal results for this dev build: [.zip](https://www.virustotal.com/gui/file/f9d950ce609a3789861808d7a58d1621b033772b7a57977cab2f4f5566fe106e/detection), [.msi](https://www.virustotal.com/gui/file/093b3f8d3aa42f604c3586c67d1c39e8e7bf8e6ac4b7fa8e155e534fe47f1c81/detection), [.exe in .zip](https://www.virustotal.com/gui/file/1f447f1548ad7699d14168fc92e73cf2d452c9ce7153bc99eab68d1c2ca48e06/detection). I can't run it that way.

**Comment by kefir500** [comment] 2020-03-30 07:58
I believe this is a false positive as there are only 1-2 antivirus engines detecting the files. The developer builds are automatically created at the trusted continuous integration services such as Travis CI (Linux, macOS) and AppVeyor (Windows).

Though it is possible to submit a false positive report to an antivirus vendor, a new developer release is created on **every** commit which are very frequent. So by the time the false positive report is reviewed, the binary itself would be already outdated.

- You can review the AppVeyor build logs here: [MSI](https://ci.appveyor.com/project/kefir500/apk-editor-studio/build/job/yr3976475kqg5jj4) / [ZIP](https://ci.appveyor.com/project/kefir500/apk-editor-studio/build/job/7xjdygf6ybt2x6ou)
- You can compile APK Editor Studio from [source](https://github.com/kefir500/apk-editor-studio/tree/1.4.0) yourself.
- You can wait for a final v1.4.0 release.

**Comment by h-h-h-h** [comment] 2020-03-30 21:49
Thanks. I'll wait for v1.4.0.

**Comment by kefir500** [comment] 2020-06-02 16:37
@h-h-h-h, in case you have checked the new release, can I have your feedback? Is the issue resolved?

**Comment by kefir500** [comment] 2020-06-30 08:22
Closing as fixed. Reopen if needed.

**Closed by kefir500** 2020-06-30 08:22 UTC
Labels: Bug
