### ISSUE TITLE
Error Packing APK

### ISSUE THREAD

**Issue by Alexandr787** [kefir500/apk-editor-studio#125] opened 2023-07-22 21:39 UTC
Hello, I get an error when I want to repackage the APK without making any changes. The error I got is below. I am using the latest version. Could you help.

```
I: Using Apktool 2.7.0
I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes.dex file...
I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes3.dex file...
I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes5.dex file...
I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes2.dex file...
I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes4.dex file...
I: Building resources...
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:796: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:803: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:810: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:817: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:824: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:831: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:838: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:845: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:852: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:859: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:866: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:873: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:880: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:887: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:894: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:901: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:908: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:915: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:922: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:929: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_125507129579507786465518122980561031691.tmp, link, -o, /tmp/APKTOOL7990709501098414879.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 2147483647, --version-name, 2.23.9.75, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL9188545717633271516.tmp, -0, arsc, -I, /home/ezel/.config/apk-editor-studio/frameworks/1.apk, --manifest, /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml, /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/build/resources.zip]
```

_Originally posted by @ByEzel93 in https://github.com/kefir500/apk-editor-studio/issues/121_

**Comment by kefir500** [comment] 2023-08-07 10:02
Could you please share the name of the APK?

**Comment by root-kernelhacker** [comment] 2023-08-07 10:11
> Hello, I get an error when I want to repackage the APK without making any changes. The error I got is below. I am using the latest version. Could you help.
> 
> ```
> I: Using Apktool 2.7.0
> I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes.dex file...
> I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes3.dex file...
> I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes5.dex file...
> I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes2.dex file...
> I: Copying /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39} classes4.dex file...
> I: Building resources...
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:796: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:803: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:810: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:817: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:824: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:831: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:838: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:845: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:852: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:859: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:866: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:873: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:880: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:887: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:894: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:901: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:908: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:915: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:922: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> W: /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml:929: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_125507129579507786465518122980561031691.tmp, link, -o, /tmp/APKTOOL7990709501098414879.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 2147483647, --version-name, 2.23.9.75, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL9188545717633271516.tmp, -0, arsc, -I, /home/ezel/.config/apk-editor-studio/frameworks/1.apk, --manifest, /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/AndroidManifest.xml, /tmp/apk-editor-studio/apk/{b9239e21-0121-4a51-9790-50de007d7f39}/build/resources.zip]
> ```
> 
> _Originally posted by @ByEzel93 in #121_

In my case, I had a similar experience when the jre version, apktool.jar version, and window environment settings did not match.  The environment where I work safely without errors is to use openjdk-build-19.0.2+7-44 / apktool_2.8.1.jar / apk-editor-studio-windows-1.7.1.  openjdk receives the distribution from github jadx, copies the jre folder to the system root, sets the environment (Windows PATH setting), and uses the update function of this tool to update the rest.  So far this configuration has had no problems unpacking and repacking the APK.  (including smali files) Hope this helps.

**Comment by kefir500** [comment] 2023-08-08 03:14
Closing as duplicate of #121.

**Closed by kefir500** 2023-08-08 03:14 UTC
Labels: Duplicate
