### ISSUE TITLE
adb install wrong success message

### ISSUE THREAD

**Issue by iAndyHD3** [kefir500/apk-editor-studio#43] opened 2021-08-18 09:37 UTC
I was trying to install my apk with adb like I was doing the past days and my APK wasnt really installing.
I got the Install APK done message when in fact it wasnt installed correctly. I uninstalled the apk on my device, tried to install with adb and still the apk didnt appear.
![image](https://user-images.githubusercontent.com/54410739/129873519-51246ede-56f4-4a86-a529-47f198222ec8.png)

Turns out that it was still installed, the apk didnt install but APK Editor Studio was returning done which confused me a lot. 
When I tried to install it through normal adb is when I realized that the apk was already installed, I think that it should return an error message rather than done. 
![image](https://user-images.githubusercontent.com/54410739/129875115-f0676e5d-b9ca-4067-b14c-10dc36bc2eda.png)

**Comment by kefir500** [comment] 2021-09-07 20:46
Hi @iAndyHD3,
Sorry for the delay.

That's a pretty weird issue, and I couldn't reproduce it.
APK Editor Studio runs the following command to install an APK:
```
adb install -r apk/to/install
```
Note the `-r` key. It **reinstalls** an app if installed, so there should be no errors regarding the already existing apps.

Couple of questions to narrow down the search:
- Were there any changes in the version code between the installed and the installable APKs?
- What was your initial reason (before you tested it manually in the command line) to believe that the APK wasn't installed correctly? Probably, the old icon, the old app title, etc.

**Comment by iAndyHD3** [comment] 2021-09-07 23:35
Hello,
Thanks for the answer.

I knew the apk was not being installed correctly when I uninstalled the apk manually from my device (I uninsalled the apk manually when I started to notice that the apk was not updating)  and then using the adb installation. 
I haven't found the solution but I found out that the problem is not APK Editor Studio:
I tried
`adb install -r .apk`
in the command line and I got the same results, it said success but the apk was not installed which means that the issue is obviously not from APK Editor Studio, tried the same with another apk to see if it is an issue with that specific APK but same result.

It's true that this is a very weird issue, I uninstall the apk manually and the apk dissapears, after that
`adb install .apk`
says that it is already installed

`adb install -r .apk`
says success but the app doesn't appear

after that I run
`adb shell pm list packages`
to check if the apk is found but it's not

Seems like the uninstall feature is broken on my device (`adb uninstall .apk` works)
Feel free to close the issue since it's a problem with my device and not APK Editor Studio
I don't think the device info helps but just in case

Huawei Mate 10 Lite
Android & EMUI 8.0

**Comment by kefir500** [comment] 2021-09-08 09:59
You can try your luck on the subject-related forums, such as XDA Developers.

Sometimes the apps are getting cached. It can involve the app icon, app title, or even the initialization stage in certain cases. Though this is not directly related to your problem, it gave me an idea for future releases to add an option to **un**install/install an app along with the **re**install.

Anyway, I hope you'll solve your issue.

Closing as not related to the APK Editor Studio. Reopen if needed.

**Closed by kefir500** 2021-09-08 09:59 UTC
Labels: Tools, APK Installation
