### ISSUE TITLE
Error packing apk (exit code = -1073741795)

### ISSUE THREAD

**Issue by Jadjld** [kefir500/apk-editor-studio#47] opened 2021-09-14 02:08 UTC
I just changed the minimum SDK and got this error:

I: Copying C:\Users\Jose_alberto\AppData\Local\Temp\apk-editor-studio\apk\{83db5205-760f-41a0-9731-e10d36628c53} classes.dex file...
I: Copying C:\Users\Jose_alberto\AppData\Local\Temp\apk-editor-studio\apk\{83db5205-760f-41a0-9731-e10d36628c53} classes2.dex file...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741795): [C:\Users\JOSE_A~1\AppData\Local\Temp\brut_util_Jar_16418201016540944904885590755305668709.tmp, compile, --dir, C:\Users\Jose_alberto\AppData\Local\Temp\apk-editor-studio\apk\{83db5205-760f-41a0-9731-e10d36628c53}\res, --legacy, -o, C:\Users\Jose_alberto\AppData\Local\Temp\apk-editor-studio\apk\{83db5205-760f-41a0-9731-e10d36628c53}\build\resources.zip]

Some help? Thanks in advance

**Comment by kefir500** [comment] 2021-09-14 09:16
Hi @Jadjld,
What OS and Java version are you using?

**Comment by Jadjld** [comment] 2021-09-14 18:10
Hi @kefir500 I am using Windows 7 Ultimate 32bit and Jre 1.8.0

**Comment by kefir500** [comment] 2021-09-15 18:40
- Does this happen to other APKs, too?
- Does this happen when you re-save your APK without changing anything?
- AFAIK, Apktool requires a 64-bit system. Maybe this is the case.

**Comment by Jadjld** [comment] 2021-09-15 18:57
• Yes, I have tried several and they all give the same error

• Yep

• That's right but in the log it says that it starts using Apktool 2.5.0 that if I'm not wrong, it still supports 32-bit, so I don't think that's exactly the problem

I also want to add that in V1.4.0 I had no problem...

**Comment by kefir500** [comment] 2021-09-15 19:17
APK Editor Studio v1.4.0 is using Apktool 2.4.1.
APK Editor Studio v1.5.0 is using Apktool 2.5.0.

According to the Apktool [changelog](https://ibotpeaches.github.io/Apktool/changes/#v250), the 32-bit version was deprecated in 2.5.0. I'm not familiar with Java, so I'm also not sure why it still passes the execution stage. However, giving the above, your 32-bit system still might be the case.

If you want, you can downgrade your Apktool by downloading [2.4.1](https://github.com/iBotPeaches/Apktool/releases/download/v2.4.1/apktool_2.4.1.jar) and providing the path to it via `Settings` → `Options` → `Repacking` → `Apktool path`.

Also, check out [this issue](https://github.com/iBotPeaches/Apktool/issues/2480) in the Apktool repo.

Closing the issue as not related to APK Editor Studio.

**Closed by kefir500** 2021-09-15 19:17 UTC
Labels: Apktool, Tools

**Comment by gncerkan** [comment] 2025-02-23 21:05
**Error packing APK.**
Hello. I wanted to use the app to change name and icon but after clicking “save APK” i get error like this. 
My app version is 1.7.2 and Apktool version is 2.11.0. I also installed Java and Visual C+. 
I also changed the “extraction path” path but the problem is not solved.
Please help me. 
```
I: Using Apktool 2.11.0 on tvQuickActionsPro_v3.5.4.apk with 8 threads
I: Copying raw classes.dex file...
I: Building resources with aapt2...
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\raws.xml:3: error: invalid value for type 'raw'. Expected a reference.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\raws.xml: error: file failed to compile.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\xmls.xml:3: error: invalid value for type 'xml'. Expected a reference.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\xmls.xml: error: file failed to compile.
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mustafa\AppData\Local\Temp\brut_util_Jar_13568560043197526301127540768758976464.tmp, compile, --dir, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res, --legacy, -o, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\build\resources.zip]
	at brut.androlib.AaptInvoker.invoke(SourceFile:0)
	at brut.androlib.ApkBuilder.buildResources(SourceFile:0)
	at brut.androlib.ApkBuilder.build(SourceFile:0)
	at brut.apktool.Main.main(SourceFile:0)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mustafa\AppData\Local\Temp\brut_util_Jar_13568560043197526301127540768758976464.tmp, compile, --dir, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res, --legacy, -o, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\build\resources.zip]
	at brut.util.OS.exec(SourceFile)
	... 4 more
```
